language: ruby
rvm:
  - 2.6

services:
  - docker

env:
  - JEKYLL_ENV=production


before_script:
  - node -v
  # update npm
  - npm install npm -g
  - git clone --depth 1 https://github.com/AKSW/aksw.org-model.git /tmp/aksw-model
  - docker run -p 3030:3030 -v /tmp/aksw-model:/staging -d stain/jena-fuseki /jena-fuseki/fuseki-server --file=/staging/aksw.org.nt /aksw

script:
  - npm install
  - npx webpack
  - bundle install
  - bundle exec jekyll build

deploy:
  - provider: pages
    skip-cleanup: true
    local_dir: _site/
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    local_dir: _site/
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target_branch: staging
    on:
      branch: develop
