baseurl: "/aksw.org.jekyllrdf" # the subpath of your site, e.g. /blog
url: "https://aksw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
rootresource: "<http://aksw.org/>"

plugins:
   - jekyll-rdf
   - jekyll-include-cache

# Jekyll RDF settings
jekyll_rdf:
    baseiri: "http://aksw.org"
    remote:
      endpoint: "http://fuseki:3030/aksw/query"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"http://aksw.org/\") }"
    default_template: "default"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Organization": "group"
        "http://rdfs.org/ns/void#Dataset": "dataset"
        "http://xmlns.com/foaf/0.1/Person": "person"
        "http://xmlns.com/foaf/0.1/Project": "project"
