baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aksw.org" # the base hostname & protocol for your site, e.g. http://example.com
rootresource: "<http://aksw.org/>"

assets_baseurl: "https://static.aksw.org/assets/"

plugins:
   - jekyll-rdf
   - liquid-md5
   - jekyll-include-cache

# Exclude files from moving them to _site
exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - Taskfile.yml
  - README.md
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules

# Jekyll RDF settings
jekyll_rdf:
    baseiri: "http://aksw.org"
    remote:
      endpoint: "http://aksw.org_model:3030/aksw/query"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"http://aksw.org/\") }"
    default_template: "default"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Group": "group"
        "http://xmlns.com/foaf/0.1/Organization": "group"
        "http://rdfs.org/ns/void#Dataset": "dataset"
        "http://xmlns.com/foaf/0.1/Person": "person"
        "http://schema.org/Event": "event"
        "http://xmlns.com/foaf/0.1/Project": "project"
