version: '3'

vars:
  TARGET: _site
  WORKING_DIRECTORY: '{{.github.workspace | default .PWD}}'
  ID_UID:
    sh: id -u
  ID_GID:
    sh: id -g
  JEKYLL_UID: '{{.JEKYLL_UID | default .ID_UID}}'
  JEKYLL_GID: '{{.JEKYLL_GID | default .ID_GID}}'

tasks:
  install:
    - npm install

  build:
    - task: build-style
    - task: build-page-local

  serve:
    - task: build-style
    - task: serve-page-local

  build-style:
    - npm run build

  serve-page-local:
    - bundle exec jekyll serve --config _config.yml,_config.local.yml -d {{.TARGET}}

  build-page-docker:
    - |
      docker run --rm \
      --workdir /github/workspace \
      -v {{.WORKING_DIRECTORY}}:/github/workspace \
      --network container:aksw.org_model \
      -e TZ=Europe/Berlin -e JEKYLL_UID="{{.JEKYLL_UID}}" -e JEKYLL_GID="{{.JEKYLL_GID}}" \
      docker.io/jekyll/builder jekyll build -d {{.TARGET}}

  build-page-local:
    - bundle exec jekyll build --config _config.yml,_config.local.yml -d {{.TARGET}}

  model-init:
    - git clone git@github.com:AKSW/aksw.org-model.git .aksw-model

  model-update:
    - cd .aksw-model
    - git pull

  model-serve:
    - docker run -p 3030:3030 --name aksw.org_model -v .aksw-model/:/graph -d docker.io/stain/jena-fuseki /jena-fuseki/fuseki-server --file=/graph/aksw.org.nt /aksw

  model-serve-stop:
    - docker stop aksw.org_model
