PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX fam: <http://www.ifi.uio.no/INF3580/family#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sysont: <http://ns.ontowiki.net/SysOnt/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aair: <http://xmlns.notu.be/aair#>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX aksw: <http://aksw.org/schema/>
PREFIX site: <http://ns.ontowiki.net/SysOnt/Site/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
